djangonautic/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

djangonautic/articles/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='articles'

urlpatterns = [
    path('',views.article_list,name="list"),
    path('create/',views.article_create,name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),
    
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),
    path('about/', views.about),
    path('', article_views.article_list,name="home"),
]

urlpatterns+=staticfiles_urlpatterns() #
urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='default.png',blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    #add thumbnail,author 
    
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]

#Note that whenever you make change to a model , you have to miograte those changes

djangonautic/articles/forms.py
#all form for this app are here
from django import forms
from . import models

#a form is a class in python
class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article #which model we are using in the form
        fields=['title','body','slug','thumb'] 

djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.

def signup_view(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save() #this function saves the form and returns the user to us
            login(request,user)
            return redirect('articles:list')
    else:
        form=UserCreationForm()
    return render(request,'accounts/sign_up.html',{'form':form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            #log in
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
    
#its better practice to use POST request than GET requets while logging the user out 
#(i.e clicking nay button rather than visiting any site)

def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

djangonautic/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles= Article.objects.all().order_by('date') #grabs all data from Article table (class in models.py represent a table in the database)
    return render(request,'articles/article_list.html',{'articles':articles}) # when we render our page( i.e article_list.html) we want to send the data retrieved in above line

def article_detail(request,slug):
    #return HttpResponse(slug)
    article=Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method=='POST':
        #if the method is post then we want to take the data that we retrieved from the 
        #create article form
        form=forms.CreateArticle(request.POST,request.FILES)
        #request.POST is validating the data that we recieved from our post (note that files(we gave an option to uplaod pics in create article form) do not come alongwith post data, we have to mention it separately)
        #the above function is validating that data
        if form.is_valid():
            #save articel to database
            instance=form.save(commit=False) #form.save anything to database, form.save returns instance of the form or the aricle
            #commit=false says do not save immediatly, we may tinker around with the instance( like we do now to set the user name automatically and then we will save the instance in the database)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
        
    else:
        form=forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

djangonautic/djangonautic/views.py
from django.http import HttpResponse #alows us to send response to users
from django.shortcuts import render #allows us to render html template 

#function which is aclled when about url is done
def about(request):
    #return HttpResponse('about') 
    return render(request,'about.html')

def homepage(request):
    #return HttpResponse('home')
    return render(request,'homepage.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Login</h1>
<form  class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
<input type="submit" value="Login">
</form>

{% endblock %}

djangonautic/accounts/templates/accounts/sign_up.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Signup</h1>
<form  class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
<input type="submit" value="Signup">
</form>

{% endblock %}

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-article">

    <h2>create an Awesome article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data"> 
         <!-- last parameter necessary for uplaod fields -->
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
    
</div>


{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">

    <div class="article">
        <img src="{{ article.thumb.url }}" >
        <h2>{{ article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.body}}</p>

    </div>
</div>    


{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}



{% block content %}
    <h1>articles list</h1>
    <div class="articles">
        {% for article in articles %}
        <div class="article">
            <h2>
                <a href="{% url 'articles:detail' article.slug %}">{{ article.title }}</a>
            </h2>
            <p>
                {{ article.snippet }}
            </p>
            <p>{{ article.date }}</p>
        </div>
    
        {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is the about page</h1>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <!-- this is the layout of the base template.the specific content to each template would come in the body i.e  here -->
    <div class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'space.png' %}"></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
                </li>
                <li>
                <a href="{% url 'articles:create' %}" class="highlight">New Article</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:login' %}">Login</a>
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is the homepage</h1>
</body>
</html>